"""add job lifecycle fields

Revision ID: 388e69874bd6
Revises: 64f45bd56074
Create Date: 2026-04-25 12:50:44.011244

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "388e69874bd6"
down_revision: Union[str, Sequence[str], None] = "64f45bd56074"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs", sa.Column("started_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "jobs", sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("jobs", sa.Column("error_code", sa.String(length=50), nullable=True))
    op.add_column(
        "jobs", sa.Column("error_message", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "error_message")
    op.drop_column("jobs", "error_code")
    op.drop_column("jobs", "finished_at")
    op.drop_column("jobs", "started_at")
    # ### end Alembic commands ###
