"""add job retry_count field

Revision ID: b8aca45600cf
Revises: 388e69874bd6
Create Date: 2026-04-25 13:54:17.251449

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b8aca45600cf"
down_revision: Union[str, Sequence[str], None] = "388e69874bd6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add NOT NULL column with server default of 0 for existing rows
    op.add_column(
        "jobs",
        sa.Column("retry_count", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "retry_count")
    # ### end Alembic commands ###
